import type { CardMatch, CardRecognizer, ScanDebug, ScanPass } from '../types.ts'
import { decodeDescriptor, describeWindows } from '../pipeline/descriptor.ts'
import { fuseCandidates, matchDescriptor } from '../pipeline/match.ts'
import type { Candidate, ReferenceCard } from '../pipeline/match.ts'
import { queryWindowRects, rectifyCard } from '../pipeline/rectify.ts'
import type { RectifyMode } from '../pipeline/rectify.ts'
import { createCapture } from './frame.ts'
import { BUILT_FROM, REFERENCE_ROWS } from './references.ts'

/**
 * The card recognizer: reticle capture -> rectify -> describe -> match.
 *
 * No model weights, no inference runtime, no network request. The "model" is
 * ~21 kB of precomputed descriptors generated by `npm run descriptors`, and the
 * arithmetic that consumes them is a few hundred lines in `pipeline/`. That is a
 * deliberate starting point rather than a stopgap: the roster is a closed set
 * with one reference image per card, which is a retrieval problem, and retrieval
 * does not need a trained classifier to answer it.
 *
 * Measure before replacing any of it — `npm run scan:eval` reports top-1 and
 * top-5 recall against real photos, and `pipeline/descriptor.ts` documents what
 * to swap in if those numbers come back short.
 */

/**
 * How many candidates `recognize` returns.
 *
 * More than the one the UI leads with, because a still is analysed once and so
 * the ranking is stable enough to show: when the top match is unconvincing, the
 * page offers the runners-up rather than a bare failure. Returning them costs
 * nothing — the matcher has already scored every card.
 *
 * Ten rather than five since the ranking became a fusion of two passes. Fusing
 * moves cards around in the tail — a card either pass ranked sixth can land
 * fourth once both are counted, and vice versa — so the list the user can
 * actually pick from should be long enough to still contain the right card when
 * the fusion reorders it. Ten rows of art is also about as far as someone will
 * scan before retaking the photo instead.
 */
const RESULT_LIMIT = 10

/**
 * The geometry passes every capture goes through, whose rankings are then fused.
 *
 * Both, rather than a choice between them, because the two fail on different
 * photos: `detect` corrects perspective but can lock onto a table seam and warp
 * the wrong quad with total confidence, while `framed` cannot be wrong about
 * *where* the card is but never corrects anything. Neither failure is detectable
 * from inside the pass that made it — which is the argument for running both and
 * letting agreement between them carry the ranking. See `fuseCandidates`.
 *
 * The cost is one extra warp and one extra pass over the reference table, both
 * of which are small next to the capture itself. Adding a third pass here is the
 * cheapest experiment in the feature; removing one is the cheapest way back to
 * a single path.
 */
const RECTIFY_MODES: readonly RectifyMode[] = ['detect', 'framed']

function decodeReferences(): ReferenceCard[] {
  return REFERENCE_ROWS.map(([artId, characterId, encoded]) => ({
    artId,
    characterId,
    descriptor: decodeDescriptor(encoded),
  }))
}

const toMatch = (candidate: Candidate): CardMatch => ({
  characterId: candidate.characterId,
  artId: candidate.artId,
  confidence: candidate.confidence,
})

export function createRecognizer(): CardRecognizer {
  let references: ReferenceCard[] = []
  let capture: ReturnType<typeof createCapture> | null = null

  /**
   * The whole pipeline, keeping what it passed through.
   *
   * `recognize` and `inspect` are both thin wrappers on this rather than two
   * implementations, so Debug Mode cannot show a region or a quad that differs
   * from the one the matcher actually scored — the failure mode a separate debug
   * path invites, and the one that makes debug output worse than none.
   */
  function run(
    frame: CanvasImageSource,
    options: { trace?: boolean } = {},
  ): { matches: CardMatch[]; debug: ScanDebug } | null {
    if (!capture || references.length === 0) return null

    const region = capture.capture(frame)
    if (!region) return null

    // Every pass sees the same region: they differ in how they flatten it, not
    // in what they were handed, so the fusion downstream compares like with
    // like. Only `inspect` asks for the trace — `recognize` would allocate the
    // corner search's intermediates and drop them on the floor.
    const passes: ScanPass[] = RECTIFY_MODES.map((mode) => ({
      mode,
      ...rectifyCard(region, { trace: options.trace, mode }),
    }))

    // How the card is cropped depends on what the references describe — the
    // generated table says which, so the two can never silently disagree.
    const rankings = passes.map((pass) =>
      matchDescriptor(
        describeWindows(pass.card, queryWindowRects(pass.card, BUILT_FROM)),
        references,
      ),
    )
    const matches = fuseCandidates(rankings).slice(0, RESULT_LIMIT).map(toMatch)

    return { matches, debug: { region, passes } }
  }

  return {
    async load() {
      // Synchronous work in an async method on purpose: `load` is part of the
      // interface because a real model would need the await, and keeping the
      // shape means swapping one in later changes this file and nothing else.
      references = decodeReferences()
      capture = createCapture()
    },

    async recognize(frame) {
      return run(frame)?.matches ?? []
    },

    async inspect(frame) {
      return run(frame, { trace: true })
    },

    dispose() {
      references = []
      capture = null
    },
  }
}
