import type { CardMatch, CardRecognizer } from '../types.ts'
import { decodeDescriptor, describeWindows } from '../pipeline/descriptor.ts'
import { matchDescriptor } from '../pipeline/match.ts'
import type { Candidate, ReferenceCard } from '../pipeline/match.ts'
import { artWindowRects, rectifyCard } from '../pipeline/rectify.ts'
import { createVoteWindow } from '../pipeline/vote.ts'
import { createCapture } from './frame.ts'
import { REFERENCE_ROWS } from './references.ts'

/**
 * The card recognizer: reticle capture -> rectify -> describe -> match -> vote.
 *
 * No model weights, no inference runtime, no network request. The "model" is
 * ~21 kB of precomputed descriptors generated by `npm run descriptors`, and the
 * arithmetic that consumes them is a few hundred lines in `pipeline/`. That is a
 * deliberate starting point rather than a stopgap: the roster is a closed set
 * with one reference image per card, which is a retrieval problem, and retrieval
 * does not need a trained classifier to answer it.
 *
 * Measure before replacing any of it — `npm run scan:eval` reports top-1 and
 * top-5 recall against real photos, and `pipeline/descriptor.ts` documents what
 * to swap in if those numbers come back short.
 */

/**
 * How many candidates `recognize` returns.
 *
 * The UI only shows the leader today, but a short ranked list is what a
 * "did you mean?" affordance would need, and returning it costs nothing — the
 * matcher has already scored every card.
 */
const RESULT_LIMIT = 5

function decodeReferences(): ReferenceCard[] {
  return REFERENCE_ROWS.map(([artId, characterId, encoded]) => ({
    artId,
    characterId,
    descriptor: decodeDescriptor(encoded),
  }))
}

const toMatch = (candidate: Candidate): CardMatch => ({
  characterId: candidate.characterId,
  confidence: candidate.confidence,
})

export function createRecognizer(): CardRecognizer {
  let references: ReferenceCard[] = []
  let capture: ReturnType<typeof createCapture> | null = null
  const votes = createVoteWindow()

  return {
    async load() {
      // Synchronous work in an async method on purpose: `load` is part of the
      // interface because a real model would need the await, and keeping the
      // shape means swapping one in later changes this file and nothing else.
      references = decodeReferences()
      capture = createCapture()
    },

    async recognize(frame) {
      if (!capture || references.length === 0) return []

      const region = capture.capture(frame)
      if (!region) return []

      const { card } = rectifyCard(region)
      const queries = describeWindows(card, artWindowRects(card))
      const ranked = matchDescriptor(queries, references)

      // Vote on the leader, then report the voted result in its place. The rest
      // of the ranking is this frame's, which is what a "did you mean?" list
      // should show — the alternatives to what is on screen right now.
      const stable = votes.push(ranked[0] ?? null)
      if (!stable) return []

      const alternatives = ranked
        .filter((candidate) => candidate.characterId !== stable.characterId)
        .slice(0, RESULT_LIMIT - 1)

      return [toMatch(stable), ...alternatives.map(toMatch)]
    },

    dispose() {
      references = []
      capture = null
      votes.reset()
    },
  }
}
