import type { CardMatch, CardRecognizer } from '../types.ts'
import { decodeDescriptor, describeWindows } from '../pipeline/descriptor.ts'
import { matchDescriptor } from '../pipeline/match.ts'
import type { Candidate, ReferenceCard } from '../pipeline/match.ts'
import { artWindowRects, rectifyCard } from '../pipeline/rectify.ts'
import { createCapture } from './frame.ts'
import { REFERENCE_ROWS } from './references.ts'

/**
 * The card recognizer: reticle capture -> rectify -> describe -> match.
 *
 * No model weights, no inference runtime, no network request. The "model" is
 * ~21 kB of precomputed descriptors generated by `npm run descriptors`, and the
 * arithmetic that consumes them is a few hundred lines in `pipeline/`. That is a
 * deliberate starting point rather than a stopgap: the roster is a closed set
 * with one reference image per card, which is a retrieval problem, and retrieval
 * does not need a trained classifier to answer it.
 *
 * Measure before replacing any of it — `npm run scan:eval` reports top-1 and
 * top-5 recall against real photos, and `pipeline/descriptor.ts` documents what
 * to swap in if those numbers come back short.
 */

/**
 * How many candidates `recognize` returns.
 *
 * More than the one the UI leads with, because a still is analysed once and so
 * the ranking is stable enough to show: when the top match is unconvincing, the
 * page offers the runners-up rather than a bare failure. Returning them costs
 * nothing — the matcher has already scored every card.
 */
const RESULT_LIMIT = 5

function decodeReferences(): ReferenceCard[] {
  return REFERENCE_ROWS.map(([artId, characterId, encoded]) => ({
    artId,
    characterId,
    descriptor: decodeDescriptor(encoded),
  }))
}

const toMatch = (candidate: Candidate): CardMatch => ({
  characterId: candidate.characterId,
  artId: candidate.artId,
  confidence: candidate.confidence,
})

export function createRecognizer(): CardRecognizer {
  let references: ReferenceCard[] = []
  let capture: ReturnType<typeof createCapture> | null = null

  return {
    async load() {
      // Synchronous work in an async method on purpose: `load` is part of the
      // interface because a real model would need the await, and keeping the
      // shape means swapping one in later changes this file and nothing else.
      references = decodeReferences()
      capture = createCapture()
    },

    async recognize(frame) {
      if (!capture || references.length === 0) return []

      const region = capture.capture(frame)
      if (!region) return []

      const { card } = rectifyCard(region)
      const queries = describeWindows(card, artWindowRects(card))
      return matchDescriptor(queries, references).slice(0, RESULT_LIMIT).map(toMatch)
    },

    dispose() {
      references = []
      capture = null
    },
  }
}
