/**
 * One representative colour per card, as [r, g, b] (0-255).
 *
 * GENERATED by scripts/build-card-colors.mjs — do not edit by hand. Re-run
 * `npm run colors` after changing any art in public/cards.
 *
 * Each value is the card's dominant hue rather than its average colour: the
 * shade you'd name if asked what colour the card is. Entries are listed in hue
 * order, neutrals last. Keyed by card id, so characters, alternate versions and
 * weapons all appear here.
 */
export const cardColors: Record<string, [number, number, number]> = {
  'young-zhuge-liang': [114, 42, 38], // #722a26
  'chen-gong': [96, 60, 55], // #603c37
  'zhu-rong': [131, 59, 49], // #833b31
  'zhang-chunhua': [163, 101, 91], // #a3655b
  'meng-huo': [117, 54, 38], // #753626
  'lu-su': [153, 94, 79], // #995e4f
  'taishi-ci': [134, 67, 49], // #864331
  'yuan-shao': [154, 43, 12], // #9a2b0c
  'ma-chao': [94, 51, 38], // #5e3326
  'zhang-jiao': [131, 61, 39], // #833d27
  'lu-bu': [91, 40, 22], // #5b2816
  'ling-tong': [121, 79, 63], // #794f3f
  'fa-zheng': [129, 57, 28], // #81391c
  'diao-chan-2': [135, 87, 67], // #875743
  'lu-xun': [154, 81, 49], // #9a5131
  'wu-guotai': [78, 33, 13], // #4e210d
  'xu-shu': [97, 46, 22], // #612e16
  'liu-bei': [160, 75, 34], // #a04b22
  'zhuge-liang': [91, 61, 46], // #5b3d2e
  'wei-yan': [102, 55, 31], // #66371f
  'cao-cao': [124, 62, 30], // #7c3e1e
  'zhang-fei': [86, 57, 42], // #56392a
  'yan-liang-wen-chou': [92, 49, 26], // #5c311a
  'xiahou-dun': [83, 55, 40], // #533728
  'gao-shun': [73, 47, 33], // #492f21
  'xu-sheng': [72, 54, 43], // #48362b
  'liu-bei-2': [122, 73, 43], // #7a492b
  'guan-yu': [119, 57, 18], // #773912
  'xu-huang': [116, 89, 72], // #745948
  'ma-su': [117, 85, 63], // #75553f
  'zhao-yun': [143, 108, 83], // #8f6c53
  'zuo-ci': [155, 109, 76], // #9b6d4c
  'huang-zhong': [91, 62, 41], // #5b3e29
  'pang-de': [101, 74, 51], // #654a33
  'jiang-wei': [180, 141, 103], // #b48d67
  'guo-jia': [157, 113, 70], // #9d7146
  'zhang-zhao-zhang-hong': [142, 98, 51], // #8e6233
  'dong-zhuo': [92, 67, 39], // #5c4327
  'sun-shangxiang': [117, 85, 48], // #755530
  'fire-fan': [174, 136, 86], // #ae8856
  'axe': [187, 146, 91], // #bb925b
  'xun-yu': [197, 158, 105], // #c59e69
  'crossbow': [183, 143, 88], // #b78f58
  'kirin-bow': [192, 150, 92], // #c0965c
  'twin-swords': [191, 150, 93], // #bf965d
  'ice-sword': [191, 150, 92], // #bf965c
  'steel-sword': [190, 149, 91], // #be955b
  'serpent-spear': [186, 146, 89], // #ba9259
  'zhou-tai': [114, 91, 57], // #725b39
  'zhou-tai-2': [89, 69, 38], // #594526
  'da-qiao': [123, 91, 38], // #7b5b26
  'pang-tong': [131, 110, 75], // #836e4b
  'huang-gai': [99, 79, 42], // #634f2a
  'xiao-qiao': [174, 138, 59], // #ae8a3b
  'sun-quan': [117, 88, 15], // #75580f
  'sun-ce': [143, 125, 79], // #8f7d4f
  'gan-ning': [101, 88, 20], // #655814
  'diao-chan': [41, 124, 97], // #297c61
  'zhou-yu': [57, 117, 110], // #39756e
  'yu-ji': [52, 83, 88], // #345358
  'cao-zhi': [27, 50, 68], // #1b3244
  'deng-ai': [64, 79, 100], // #404f64
  'yu-jin': [68, 83, 115], // #445373
  'sima-yi': [38, 54, 93], // #26365d
  'xiahou-yuan': [41, 49, 70], // #293146
  'cai-wenji': [45, 51, 67], // #2d3343
  'cao-pi': [30, 38, 61], // #1e263d
  'cao-ren': [43, 49, 75], // #2b314b
  'jia-xu': [63, 68, 100], // #3f4464
  'zhang-he': [70, 64, 106], // #46406a
  'liu-shan': [141, 80, 86], // #8d5056
  'huang-yueying': [64, 66, 56], // #404238
  'cao-ren-2': [68, 71, 78], // #44474e
  'xu-zhu': [85, 82, 78], // #55524e
  'dian-wei': [87, 90, 98], // #575a62
  'yu-ji-2': [99, 104, 108], // #63686c
  'zhang-liao': [110, 109, 118], // #6e6d76
  'sun-jian': [121, 112, 101], // #797065
  'zhang-jiao-2': [124, 120, 119], // #7c7877
  'lu-meng': [131, 133, 132], // #838584
  'hua-tuo': [134, 129, 118], // #868176
  'sky-halberd': [174, 163, 148], // #aea394
  'silver-lance': [175, 163, 148], // #afa394
  'zhen-ji': [175, 162, 176], // #afa2b0
  'ancient-sword': [178, 167, 150], // #b2a796
  'dragon-blade': [178, 167, 150], // #b2a796
}
